[build]
  base = ""
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

[context.production.environment]
  NODE_ENV = "production"

[context.development.environment]
  NODE_ENV = "development"
